services:
  db_postgres:
    image: postgres:latest
    container_name: db_web
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U local -d app" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
    driver: local